version: '3.9'

networks:
  vw:
    name: vw
    driver: bridge

services:
 
  # Vaultwarden - Open Source Password Manager.
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden # change for multiple instances
    restart: always

    networks:
      - vw

    ports:
      - $VWPORTN:80
      - 3012:3012

    volumes:
      - ./vw-data:/data
      - /var/log/docker:/var/log/docker
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      - ADMIN_TOKEN=$ADMIN_TOKEN
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true # Change to false after first login
      - INVITATIONS_ALLOWED=true # Send invitation using admin page
      - LOG_FILE=/var/log/docker/bitwarden.log
      - DOMAIN=https://vw.$DOMAINNAME

  # Watchtower - automating Docker container base image updates.
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always

    networks:
      - vw

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - TZ=$TZ
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 30 5 * * * # Everyday at 5:30
